### ISSUE TITLE
Use standard URL paths to address files within the file

### ISSUE THREAD

**Issue by adrianhopebailie** [craigfrancis/wdoc#1]
The standard could support access to files within the archive by simply requiring that browsers (or whatever application is rendering the file) interpret them as such.

*Example: *

A file opened in the browser with the URL `file:///temp/example.wdoc` would display the content of the file index.html inside that archive.
If the URL was changed to `file:///temp/example.wdoc/index2.html` then the file index2.html inside the archive would be rendered.

**Comment by craigfrancis** [comment]
Thanks Adrian,

Firefox has a similar thing for JAR files, which I briefly mentioned towards the end. Personally I prefer your much shorter version, so do the examples I've just added to the document reflect this properly?

https://github.com/craigfrancis/wdoc#the-browsers

**Comment by craigfrancis** [comment]
I forgot to say, thanks for your initial email on the [W3C WebAppSec mailing list](https://lists.w3.org/Archives/Public/public-webappsec/2016Jan/0064.html) ... this is how I found out about the Firefox approach.

I also like your `.hta` extension idea, where someone else has a similar idea with [.hdoc](http://hdoc.crzt.fr/www/co/hdocConverter.html), but as far as I can tell, nothing has actually used `.wdoc` yet :-)

**Comment by adrianhopebailie** [comment]
LGTM
